export const ADD = 'ADD';
export const SUB = 'SUB';

export const HEALTH = 'HEALTH';
export const HEALTH_STATUS = 'HEALTH_STATUS';

export const SYSTEM_ERROR = 'SYSTEM_ERROR';

// for MetaMask
export const METAMASK_ACCOUNT = 'METAMASK_ACCOUNT';
export const METAMASK_NETWORK = 'METAMASK_NETWORK';

// for SimpleToken contract
export const SIMPLE_TOKEN_NAME = 'SIMPLE_TOKEN_NAME';
export const SIMPLE_TOKEN_NAME_SUCCESS = 'SIMPLE_TOKEN_NAME_SUCCESS';
export const SIMPLE_TOKEN_SYMBOL = 'SIMPLE_TOKEN_SYMBOL';
export const SIMPLE_TOKEN_SYMBOL_SUCCESS = 'SIMPLE_TOKEN_SYMBOL_SUCCESS';
export const SIMPLE_TOKEN_DECIMALS = 'SIMPLE_TOKEN_DECIMALS';
export const SIMPLE_TOKEN_DECIMALS_SUCCESS = 'SIMPLE_TOKEN_DECIMALS_SUCCESS';

// for showing progress/onloading
export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';

// for showing warning message
export const WARNING_OPEN = 'WARNING_OPEN';
export const WARNING_CLOSE = 'WARNING_CLOSE';

// for Bluzelle 
export const BLUZELLE_CREATE = 'BLUZELLE_CREATE';
export const BLUZELLE_CREATE_SUCCESS = 'BLUZELLE_CREATE_SUCCESS';
export const BLUZELLE_CREATE_FAILED = 'BLUZELLE_CREATE_FAILED';
export const BLUZELLE_UPDATE = 'BLUZELLE_UPDATE';
export const BLUZELLE_UPDATE_SUCCESS = 'BLUZELLE_UPDATE_SUCCESS';
export const BLUZELLE_UPDATE_FAILED = 'BLUZELLE_UPDATE_FAILED';
export const BLUZELLE_REMOVE = 'BLUZELLE_REMOVE';
export const BLUZELLE_REMOVE_SUCCESS = 'BLUZELLE_REMOVE_SUCCESS';
export const BLUZELLE_REMOVE_FAILED = 'BLUZELLE_REMOVE_FAILED';
export const BLUZELLE_READ = 'BLUZELLE_READ';
export const BLUZELLE_READ_SUCCESS = 'BLUZELLE_READ_SUCCESS';
export const BLUZELLE_READ_FAILED = 'BLUZELLE_READ_FAILED';
export const BLUZELLE_KEYS = 'BLUZELLE_KEYS';
export const BLUZELLE_KEYS_SUCCESS = 'BLUZELLE_KEYS_SUCCESS';
export const BLUZELLE_KEYS_FAILED = 'BLUZELLE_KEYS_FAILED';
